### ISSUE TITLE
1.0.0: TypeError, cannot read property config of null

### ISSUE THREAD

**Issue by eemt** [postcss/postcss-loader#115]
Doesn't really cause a problem, but FYI: 

After updating from 0.13.0, to 1.0.0, when running webpack, I get the following warning: 

`TypeError: Cannot read property 'config' of null at postcss-load-config\index.js:50:22`

We have: 

- node: v6.7.0
- npm: 3.10.5
- webpack: 1.13.2
- babel-core: 6.17.0

Windows dev environment. 

We do not have a **postcss-load-config**.

Our webpack, postcss-loader entry is: 
```
    module: {
      loaders: [
        {
          test: /\.s?css$/,
          loaders: ['style', 'css', 'postcss-loader?browsers=last 2 versions', 'sass'],
          include: PATHS.app
        }
      ]
    },
```

**Comment by ai** [comment]
You could not do like this

```
postcss-loader?browsers=last 2 versions
```

`browsers` is a `autoprefixer` options. `postcss` accepts only plugins list and syntax options.

Please, read docs more careful.

**Comment by ai** [comment]
Autoprefixer browsers should be in `browserslist` config.

**Comment by ai** [comment]
You have

```
TypeError: Cannot read property 'config' of null at postcss-load-config\index.js:50:22
```

warning because you didn’t set common PostCSS config (with Autoprefixer)

**Comment by ai** [comment]
I added `browserslist` to docs: ec2b13e

**Comment by dkrutsko** [comment]
Hey, I'm actually having the same problem and I don't think it's because of autoprefixer.

Here's my error message:
```bash
TypeError: Cannot read property 'config' of null
    at postcss-load-config/index.js:50:22
```

Here's my loader config:
```js
loader: "postcss",
query : {
	plugins()
	{
		return [
			// Plugins
		];
	}
}
```

I don't minimize my CSS with css-loader so it shouldn't be doing double autoprefixing. I also don't have a postcss-load-config file.

**Comment by ai** [comment]
@dkrutsko this warning is temporary problem of `postcss-load-config`. `postcss-load-config` shows this warning when it could not find a config.

Real problem is that you use wrong syntax and PostCSS doesn’t see a plugins that you set. So PostCSS loader try to look for config and show this warning.

@dkrutsko why you write plugins in `query` key? We recommends common PostCSS config.

If you don’t want to use common PostCSS config (it is not a good idea) you should set plugins in `options` key, not `query`.

**Comment by dkrutsko** [comment]
@ai: Yeah I changed it to options but that error never went away. But like you said, just a temporary solution that will get fixed soon, right?

The reason I use query and not options is because of the early versions of webpack. I still can't find any up to date documentation on the later changes so I'm assuming that rules/loaders and options/query are interchangeable. If I use query will it not work? What about sourceMaps can I do something like this:

```js
loader: "postcss",
query : {
	sourceMap: true,
	plugins() { ... }
}
```

**Comment by ai** [comment]
@dkrutsko check our documentation :) we wrote how to set loader options https://github.com/postcss/postcss-loader#webpack-2x-config

**Comment by EvNaverniouk** [comment]
@ai I configured my webpack config to be the same as `https://github.com/postcss/postcss-loader#webpack-2x-config` but I still see these warnings still appear:
```
    at /myapp/node_modules/postcss-load-config/index.js:50:22
 66% building modules 1312/1385 modules 73 active ...form/node_modules/lodash/_nodeUtil.jsTypeError: Cannot read property 'config' of null
```

Removing:

```
options: {
	plugins () {
		return [
			require('autoprefixer')
		];
	}
}
```

makes the warning to away.

**Comment by ai** [comment]
@EvNaverniouk yeap, warnings happens because of issue in `postcss-load-config`.

I hope @michael-ciniawsky will fix it soon :).

Don’t worry about this warning, it happens because `postcss-load-config` could not find a config.
