### ISSUE TITLE
Plugins could not be passed through options in webpack 2.2.0

### ISSUE THREAD

**Issue by artemkaint** [postcss/postcss-loader#164]
If I use the constraction from the example 
```
module.exports = {
  module: {
    rules: [
      {
        test: /\.css/,
        use: [
          …
          {
            loader: 'postcss-loader',
            options: {
              plugins: function () {
                return [
                  require('precss'),
                  require('autoprefixer')
                ];
              }
            }
          }
        ]
      }
    ]
  }
}
```
I have obtain 
/opt/project/node_modules/postcss-loader/index.js?{"plugins":{"default":[null,null],"fontAwesome":[null,null]},"pack":"default"}

https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L21
Beсause all function  have been converted into string (of course null)

**Comment by artemkaint** [comment]
now we have to use ident key in options to pass function

**Comment by ai** [comment]
@TheLarkInn I need you help here. Do we need to change our current docs?
https://github.com/postcss/postcss-loader#webpack-2-1

**Comment by maratfakhreev** [comment]
Same issue, seems like `postcss.config.js` doesn't work for 2.2.0

**Comment by ai** [comment]
@maratfakhreev @artemkaint please show your full configs. In most previous cases it was not a PostCSS loader problem, but Extract Text plugin or other crazy thing.

**Comment by maratfakhreev** [comment]
@ai yeah, thx, have found the problem on my side. Loader works correctly.

**Comment by michael-ciniawsky** [comment]
@ai I work on new docs for inline config already, but I'm waiting for reply if 'this' (@example) will stay or not because I absolutely don't like it 😛  => `{ ident: 'whatever' }`  => https://webpack.js.org/guides/migrating/#complex-options

@artemkaint @maratfakhreev ⬇️ 

```js
{
  loader: 'postcss-loader',
  options: { ident: 'postcss', plugins: () => [ require('plugin') ] }
}
```

[README](https://github.com/michael-ciniawsky/postcss-loader/tree/docs) (WIP)

@ai I push (PR) them as quickly as possible, should I in addition push just the example fixes ? I also wanted to add an example for `extract-text-plugin` and we must fix it before :D.

**Comment by michael-ciniawsky** [comment]
@ai @artemkaint @maratfakhreev guys please a :shipit:  on https://github.com/webpack/webpack/pull/4073#issuecomment-274259228 👍 to get rid of `{ ident: 'crap' }` 😛

**Comment by edmundo096** [comment]
I commented a summary of possible ways to resolve this on [another (closed) issue](https://github.com/postcss/postcss-loader/issues/92#issuecomment-276036682). Here is my comment:

So basically, what I conclude after reading and some researching, there are 3 ways (**_as for now_**) to load the PostCSS configuration for Webpack 2:

1. **Using a `postcss.config.js` file**, which must be "anywhere down the file tree" where Webpack matches a file (e.g. if a match was on a `\assets\stylesheets` file, `postcss.config.js` must be anywhere inside that path). 
This is due how **postcss-loader** works. It uses **postcss-load-config** module, which uses **cosmiconfig** module (see more in [davidtheclark/cosmiconfig](https://github.com/davidtheclark/cosmiconfig)).
That is why there is almost no documentation about where one can place that file.
Placing it on the root almost assures that `postcss.config.js` *will just work*, although this is not prefered by everybody.

As a side note, since this depends mainly on **cosmiconfig** we also have other 3 ways here:
  - *package.json* property (anywhere down the file tree). An example reached reading [this](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/330#issuecomment-274217819) is [here](https://github.com/jaydenseric/Barebones/blob/v9.0.0/package.json#L63)
  - *JSON or YAML* "rc file" (anywhere down the file tree).
  -  *CLI --config argument*.
  - As already commented, *.config.js* CommonJS module (anywhere down the file tree).

2. **Using the `ident`** on the options object (as owenDods [commented](https://github.com/postcss/postcss-loader/issues/92#issuecomment-275696824)).
_**This may become unnecessary in the future if fixed.**_
```javascript
{
  loader: 'postcss-loader',
  options: {
    ident: 'postcss',     // <- This..
    plugins: () => [ require('plugin') ]
  }
}
```

3. **Using the `webpack.LoaderOptionsPlugin`**.
This makes `postcss-loader` load the options (and plugins) as if we were using Webpack 1.
See more here https://webpack.js.org/plugins/loader-options-plugin/

The last 2 are handled respectively by this line of code: `var options  = params.plugins || loader.options.postcss;` in the [index.js#L48](https://github.com/postcss/postcss-loader/blob/master/index.js#L48).
All of this 3 proaches support an array of plugins.

Hope this helps someone else (avoiding possible headaches) in the future.

**Comment by VladShcherbin** [comment]
Works for me with webpack 2.2.1:

```js
{
  test: /\.scss$/,
  loaders: [
    ...,
    {
      loader: 'postcss-loader',
      options: {
        plugins: () => [ require('autoprefixer')({ browsers: ['last 2 versions'] }) ]
      }
    },
    ...
  ]
}
```

**Comment by michael-ciniawsky** [comment]
@VladShcherbin You where faster 😛 

As a note for anyone coming here using an older webpack || extract-text-plugin version => 
1. webpack >= v2.2.1 solves bugs in `loader.options` by automatically creating an `ident` now. Options containing functions and `require()`  statements work as expected. 
2. ExtractTextPlugin is on the finish line, be aware of an API change `fallbackLoader => fallback` &&  `loader => use` before ExtractTextPlugin v2 **final**

**webpack.config.js**


```js
import ExtractText from 'extract-text-webpack-plugin'

export default {
  module: {
    rules: [
       {
          test: /\.css$/,
          include: 'path/to/includes', // optional
          exclude: 'path/to/excludes', // optional
          use: [
            'style-loader',
             { loader: 'css-loader', options: { importLoaders: 1 } },
             { 
               loader: 'postcss-loader', 
               options: { plugins: (ctx) => [ require('plugin')({ option: ctx.resourcePath }) ] }
             }
          ]
       },
       // Extract Text Plugin
       {
          test: /\.css$/,
          include: 'path/to/includes', // optional
          exclude: 'path/to/excludes', // optional
          use: ExtractText.extract({
            fallback: 'style-loader'
            use: [
               { loader: 'css-loader', options: { importLoaders: 1 } },
               { 
                 loader: 'postcss-loader', 
                 options: { plugins: (ctx) => [ require('plugin')({ option: ctx.resourcePath }) ] }
               }
             ]
          })
        }
     ]
  },
  plugins: [
    new ExtractText([name].css)
  ]
}
``` 

Closed as fixed :)
