### ISSUE TITLE
postcss.config.babel.js possible?

### ISSUE THREAD

**Issue by kud** [postcss/postcss-loader#192]
All is in the title.

**Comment by michael-ciniawsky** [comment]
@kud There is an issue open in `postcss-load-config`, but I don't intend to support it out-of-the-box, the babel deps would be bigger than the whole module itself 😛 , you can try `babel-register' and see if it works. Otherwise nope sry

**Comment by kud** [comment]
Thank you. :)

**Comment by klimashkin** [comment]
Seems like just putting `postcss.config.js` into `babel-register` doesn't work because `postcss-load-config` uses [cosmiconfig](https://github.com/davidtheclark/cosmiconfig), which reads file manually and uses [require-from-string](https://github.com/floatdrop/require-from-string).

So you need also to require `postcss.config.js` manually and assign it to loader `options` property.

**Comment by nolimitdev** [comment]
@klimashkin thanks, I have published your solution, still needed nowadays in 2023
https://stackoverflow.com/questions/77395536/postcss-config-js-does-not-support-mjs-es-modules
