### ISSUE TITLE
postcss.config.js in node_modules overriding the root postcss.config.js

### ISSUE THREAD

**Issue by pmsorhaindo** [postcss/postcss-loader#194]
I'm using a module which provides some css, which also contains a `postcss.config.js`. When I run webpack this module's `postcss.config.js` is used by the loader instead of the one in the root of my project. 

Is this intentional or should the loader always use the root config file?

```
| - postcss.config.js
| - webpack.config.js
| - node_modules
    | - module
        | - postcss.config.js <--- this gets picked up by webpack for foo.css below
        | - foo.css 
```

**Comment by michael-ciniawsky** [comment]
Hmm...:stuck_out_tongue: normally this is intentional, the config search algo starts searching from `dirname(file)` currently processed by the the loader and goes upwards until it hits the project root. You can pass a fixed config path for config lookup to disable the config cascade that way

**webpack.config.js**
```js
{
   loader: 'postcss-loader', options: { config: 'path/to/postcss.config.js' }
}
```

Can you provide a link to the module you are using, containing the `postcss.config.js`? I would like to investigate how to disable this :). And if you have the time could you try by excluding `node_modules` ?

**webpack.config.js**
```js
{ 
   test: /\.css$/,
   use: [
     ...,
     ...,
     { loader: 'postcss-loader', options: { config: 'path/to/postcss.config.js' } }
   ],
   exclude: /node_modules/
}
```

**Comment by pmsorhaindo** [comment]
Ah! Thanks @michael-ciniawsky, The config option gets me the desired functionality, 😃 thanks for pointing that out! The pattern library `bw-axiom` is the library I was using, unfortunately in this case just excluding the node_modules leads to webpack being unable to handle the cssnext `@imports` in these files.

**Comment by michael-ciniawsky** [comment]
@pmsorhaindo Still curious why it actually gets picked up, bc normally only the file containing the `@import`, should trigger config lookup :D Do you import the lib via webpack (1) or a postcss-plugin (2) `postcss-import`? `postcss-cssnext`doesn't seem to ship with an import plugin 😛 

#### (1)
**component.js** (`css-loader!postcss-loader`)
```js
import lib from 'some/lib.css'
import style from './style.css'
```

#### (2) 
```css
@import 'some/lib.css'
```

**Comment by pmsorhaindo** [comment]
Yeah, you're right. The library provides react components, which are imported via webpack. but the CSS in that library is making use of postcss-import.

**Comment by michael-ciniawsky** [comment]
yeah... 😛  still need to find a way to ignore this properly 😊. kk if still any regressions feel free to reopen or just open a new issue
