### ISSUE TITLE
Use PostCSS 6.0

### ISSUE THREAD

**Issue by ai** [postcss/postcss-loader#206]
[PostCSS 6.0](https://github.com/postcss/postcss/releases/tag/6.0.0) was released. API wasn’t changed dramatically, so you need only update dependency and release new version.

@michael-ciniawsky write me if you need any help. If you have big plans in 2.0, we can quickly release 2.0 only with PostCSS 6 and big changes move to 3.0 (it is OK to make major releases often if it has small changes).

**Comment by michael-ciniawsky** [comment]
@ai Nope 😛 let's release **v2.0.0** as quickly as possible, I only need to update docs && finish release notes I try to do it today/until tomorrow. The 'webpack CSS' related changes will take more time and blocking a new release for `postcss-loader` _way_ too long anyways 🙃. 

- Is PostCSS v6.0.0 breaking any major plugins atm?
- Sokra mentioned that the `map.names` (source maps) are 'off', they need to contain an absolute path, how can we fix it ?
- Ok to use the webpack loader README template (similiar to postcss-cli README style, I wrote 😛 ), because the folks from [webpack.js.org](https://webpack.js.org) would like to list `postcss-loader` as an common loader on the docs page then? 😊

**Comment by ai** [comment]
Sure, we can wait few days.

1. Plugin API changes are small and should not affect most of plugins.
2. What is `map.names`? Where I can read more about it?
3. Sure, you are maintainer and you can change project docs style.

**Comment by michael-ciniawsky** [comment]
> Plugin API changes are small and should not affect most of plugins

kk, should be fine when there is no known issue with something like e.g cssnext yet :)

> What is map.names? Where I can read more about it?

😆 I'm an idiot, `map.sources`  of course 😛 needs to contain absolute paths as the source **name** , maybe it'a the same 'issue' adressed [here](https://github.com/webpack-contrib/css-loader/blob/master/lib/processCss.js#L203), but not 💯  waiting for reply to confirm 

> Sure, you are maintainer and you can change project docs style

👍 😛

**Comment by michael-ciniawsky** [comment]
The `map` issue can be a bugfix release later, so a bit offtopic I get the release ready :stuck_out_tongue:

**Comment by ai** [comment]
Let’s move `map.sources` fix on next PostCSS release. Looks like we will not fix it very soon. Is it OK?

**Comment by michael-ciniawsky** [comment]
```js
if (map) {
  map.file = path.resolve(map.file)
  map.sources = map.sources.map((src) => path.resolve(src))
}
```

Done, if there is still something is flanky it's a`x.x.1` patch release, just finishing the docs an good to go 😛 (today)
