### ISSUE TITLE
v2.0.5 with postcss-attribute-case-insensitive

### ISSUE THREAD

**Issue by yiwan** [postcss/postcss-loader#242]
The log says
`Your current PostCSS version is 6.0.1, but postcss-attribute-case-insensitive uses 5.2.17. Perhaps this is the source of the error below.`

`"postcss-loader": "2.0.5"`

Then I fallback to v2.0.4, everything is fine.

**Comment by michael-ciniawsky** [comment]
That's a warning from the Plugin API && PostCSS Core since `v6` had a few breaking changes , mostly removal of old `v4` API's and `node.raws` fix, if it still works ignore this warning. Otherwise you will need to open an issue @postcss-atrribute-case-insensitive instead asking to bump PostCSS to v6, `postcss-loader >=v2.0.0` uses PostCSS `v6` I can't do anything from the loader sinde here 😟
