### ISSUE TITLE
[2.0.5] Warning emitted when options.sourceMap is explicitly false

### ISSUE THREAD

**Issue by vedadsose** [postcss/postcss-loader#253]
Even when explicitly setting `sourceMap: false`, warning is emitted:

> Previous source map found, but options.sourceMap isn't set

Looking at the source code: https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L130

It looks like the condition for emitting this warning should be:

```
if (sourceMap == undefined && map) {
      this.emitWarning(`\n\n ⚠️  PostCSS Loader\n\nPrevious source map found, but options.sourceMap isn't set.\nIn this case the loader will discard the source map entirely for performance reasons.\nSee https://github.com/postcss/postcss-loader#sourcemap for more information.\n\n`)
}
```

**Comment by evilebottnawi** [comment]
@vedadsose seems loader before `postcss-loader` emit source map (add `sourceMap: false`) for `sass/less/etc-loader`

**Comment by vedadsose** [comment]
@evilebottnawi If you think the warning should still be there even if options.sourceMap is false, then it shouldn't contain `but options.sourceMap isn't set` part.

**Comment by michael-ciniawsky** [comment]
It warns about a source map from a previous loader, since `postcss-loader` discards the source map enterily when `{ sourceMap: true }` isn't set in `postcss-loader` options, The **default** is to not generate a sourcemap for perf reasons. The warning is correct, please either set `{ sourceMap: true }` or disable source maps in any previous loader.

@evilebottnawi No please no additional options for a trivial usecase, the warning maybe annoying but it is intended to do so :), bc the config is simply incorrect

**Comment by ndbroadbent** [comment]
I really want to disable this warning, because I only need source maps for JS, and I want to explicitly disable them for CSS in production. I know webpack is still creating some empty `.css.map` files, but I'll just delete those. (There doesn't seem to be any way to only enable source maps for JS and skip CSS.)

I think setting `sourceMap: false` in `postcss-loader` should not log any warnings, since it's a valid choice.
