### ISSUE TITLE
postcss-loader can't read property of null error

### ISSUE THREAD

**Issue by taigi0315** [postcss/postcss-loader#254]
I have been try to fix this bug with google search, but couldn't find any solution works for my case
webpack version : 2.5.1

--My prod.js file
![screen shot 2017-06-07 at 11 51 47 am](https://user-images.githubusercontent.com/11429827/26890697-0e7f6c4a-4b78-11e7-9f1f-4edb671b6b69.png)
--Output error
![screen shot 2017-06-07 at 11 52 49 am](https://user-images.githubusercontent.com/11429827/26890721-233e7036-4b78-11e7-9fad-7ad39323c0bf.png)

I am a beginner in web-dev, please give me as detail answer as possible

**Comment by michael-ciniawsky** [comment]
It is safer to use a `postcss.config.js` file I highly recommend it, the reason is that in this case a webpack config related bug sometimes doesn't apply functions in `webpack.config.js`. You can ducktape it in `webpack.config.js` by using so called `ident` in the loader options :)

```js
...
{
  loader: 'postcss-loader'
  options: {
    ident: 'postcss',  // <= 
    plugins: [ require('postcss-plugin')(options), ... ]
  }
}
...
```

Also remove `style-loader` from `use` in `ExtractTextPlugin.extract` it's used as `fallback` already and extraction will fail when it is applied in the `use` chain

Use `stylus-loader` instead of `stylus-relative-loader` it seems to emit a sourcemap by default which is bad for performance

**Comment by taigi0315** [comment]
Thanks for your comment !
I followed your suggestions, still having an issue with warning (postcss)
I can build/deploy app, the problem is my Material-ui error does not show require error
---prod.config.js
<img width="441" alt="screen shot 2017-06-08 at 11 05 43 am" src="https://user-images.githubusercontent.com/11429827/26938837-0f928612-4c3b-11e7-9e9c-648b5747c3a7.png">
---postcss.config.js
<img width="387" alt="screen shot 2017-06-08 at 11 05 57 am" src="https://user-images.githubusercontent.com/11429827/26938855-1b53667e-4c3b-11e7-89e4-f70b39d458ab.png">
---Error message
![screen shot 2017-06-08 at 11 06 16 am](https://user-images.githubusercontent.com/11429827/26938865-22b80712-4c3b-11e7-8c96-044c1f60b6ad.png)

I located postcss.config.js right under the App(where the package.js goes)
if I am doing stupid mistake, please forgive me, I am a new starter who took over built project from senior developer :(

**Comment by michael-ciniawsky** [comment]
In terms of `postcss-loader` choose either `postcss.config.js` (recommended) or set **options** in `webpack.config.js`. You are doing both atm :), but that isn't are problem `webpack.config.js` > `postcss.config.js` in terms of config loading 

**webpack.config.js** (when using **postcss.config.js**)
```diff
- { loader: 'postcss-loader', options: { plugins: () => [...plugins] } }
+ 'postcss-loader'
```

Please try  `{ sourceMap: false }` in `stylus-loader` options, it is a warning and everything should still work, but the sourcemap will be discarded by `postcss-loader`

**Comment by evilebottnawi** [comment]
@michael-ciniawsky How about if your release a major where only configuration files are allowed, it would be great and solved all these problems :+1:

**Comment by taigi0315** [comment]
Thanks for the help, 
I took off `options` from webpack config, add `sourceMap : false` in `stylus-loader` as well
App builds without any warning/Error but for some reason material-ui/yup schema error does not display.(works find in de). Now I start wondering where to look to fix this.
I really thanks for your time, appreciate it !

**Comment by davidrf** [comment]
I've created a simplified [example repo that reproduces this error](https://github.com/davidrf/postcss-loader-issue-254-webpack-example). I am not entirely sure if this is a postcss-loader issue, or a Webpack issue, or an issue from something else. Adding a `postcss.config.js` file or `ident` does solve the problem, but I believe that this issue should be re-opened and remain open until one of the following occurs:

* The webpack configuration is removed from the postcss-loader README and `postcss.config.js` becomes the only configuration.
* `ident` is not longer needed for this to work with the Webpack configuration.
* An issue is opened in another repository which is causing the error. (I did look for open issues in other repositories that may explain this error, but found none)

@michael-ciniawsky would you please take a look at the example repo and weigh in on whether or not this issue is fully resolved??
