### ISSUE TITLE
Missing errors

### ISSUE THREAD

**Issue by coot** [postcss/postcss-loader#279]
It happens quite often that the there are no errors from css-modules nor postcss-loader, e.g. when a `composes` is miss formatted, like in `compose: ...` instead of `composes: ...`.  It would be nice if there were errors / warning from postcss.  In general more verbose output from postcss would be appreciated.

**Comment by michael-ciniawsky** [comment]
This is actually a `css-loader` issue, since CSS Modules are implemented there atm :). Could you reopen in `css-loader` please and I will triage it there then. It might be difficult to fix this appropiately, because all `postcss-modules-*` (CSS Modules) plugins need to emit warnings/errors to `result.messages` beforehand to get meaningful messages. `postcss-loader` throws pretty printed errors messages + code frames on [`CssSyntaxError`](https://github.com/postcss/postcss-loader/blob/master/lib/Error.js#L3) [already](https://github.com/postcss/postcss-loader/blob/master/lib/index.js#L181).
![csssyntaxerror](https://user-images.githubusercontent.com/5419992/28630772-7c15aa1a-722b-11e7-8d14-59297ff10774.png)
