### ISSUE TITLE
Migrating from Sass to PostCSS using Webpack

### ISSUE THREAD

**Issue by mlcohen** [postcss/postcss-loader#290]
Hi --

Has anyone using Sass in their web app project managed to use the `postcss-loader` to successfully transpile Sass into plain-old CSS? I ask since I'm working on a rather large web app project that makes extensive use of Sass. The project's webpack config is setup to first use the `sass-loader` (+ `node-sass`) and then use the `postcss-loader` but just so that we can use `autoprefixer`. The idea is to try and use postcss exclusively but so far we've haven't had any success. 

This is the module loader sequence we're currently using to process our Sass files:

```js
{
    test: /\.(sass|scss)$/,
    use: [{
        loader: 'css-loader',
        options: {
            modules: true,
            camelCase: true,
            importLoaders: 2,
            localIdentName: '[name]--[local]--[hash:base64:5]'
        }
    },
    {
        loader: 'postcss-loader'
    },
    {
        loader: 'sass-loader'
    }]
}
```

And here is our current `postcss.config.js` file:

```js
module.exports = {
    plugins: [
        require('autoprefixer')()
    ]
}
```

I've tried updating the postcss config to make use of `precss` along with `postcss-sass` but I'm unable to get webpack to produce CSS output (with the `sass-loader` removed).

Apologies if this is not the right forum to ask this question.

**Comment by michael-ciniawsky** [comment]
`postcss-scss` is **syntax** parsing only to my knowledge, so the migration effort depends on how much Sass **functionality** (mixins, extends etc) you currently use in your project. It will definitely take some effort. Also don't use `precss` anymore as it is deprecated and unmaintained => use the PostCSS Plugins you need standalone in `postcss.config.js` instead (`postcss-nested`, `postcss-mixins`, ...). Otherwise please ask folks in the [PostCSS Channel](https://gitter.im/postcss/postcss), if someone haas done such a migration before and if the have some tips and tricks how to do it at best
