### ISSUE TITLE
Module build failed: Error: No PostCSS Config found in

### ISSUE THREAD

**Issue by acopalipsis** [postcss/postcss-loader#304]
postcss-loader - 2.0.8
postcss - 6.0.13
webpack - 3.8.1
ubuntu - 14.04

```
// module -> rulse
{
    test: /\.(sass|scss)?$/,
    use: [
        'style-loader',
        'css-loader',
        'postcss-loader',
        'sass-loader'
    ],
    include: [ path.join( __dirname, 'src' ) ],
    exclude: /node_modules/
},
```

```
// plugins
new LoaderOptionsPlugin( {
    options: {
        context: __dirname,
        postcss: [
            cssnext( {
                browsers: [ 'last 2 versions', 'IE > 10' ],
            } ),
        ],
    },
} ),
```

> ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib!./node_modules/sass-loader/lib/loader.js!./src/main.sass
> Module build failed: Error: No PostCSS Config found in: ...

**Comment by michael-ciniawsky** [comment]
Don't use `LoaderOptionsPlugin`, it isn't needed anymore since `postcss-loader`  supports `webpack >= v2.0.0` for a long time now and I removed 'support' for `LoaderOptionsPlugin` in `postcss-loader >= v2.0.0`. The `No Config...` Error occurs bc no options from`LoaderOptionsPlugin` are passed to `postcss-loader` anymore

```diff
{
    test: /\.(sass|scss)?$/,
    use: [
        'style-loader',
        'css-loader',
-        'postcss-loader',
+     { 
+        loader: 'postcss-loader',
+        options: { 
+            ident: 'postcss', 
+            plugins: () => [ require('postcss-plugin') ]
+        }
        }
        'sass-loader'
    ],
    include: [ path.join( __dirname, 'src' ) ],
    exclude: /node_modules/
},
``` 

or use a `postcss.config.js` file
