### ISSUE TITLE
`plugins` option doc out of date?

### ISSUE THREAD

**Issue by pacahon** [postcss/postcss-loader#309]
Hello. I'm using `webpack@3.5.5` and `postcss-loader@2.0.8`. 

Following the instructions here https://github.com/postcss/postcss-loader#plugins after adding `ident` to loader options I realized that my `postcss.config.js` stopped working. 

I found this link https://webpack.js.org/guides/migrating/#complex-options

Looks like `ident` option not really necessary since 2.2.1?

**Comment by michael-ciniawsky** [comment]
If you use `postcss.config.js` the only option you need to set in `webpack.config.js` is `sourceMap` in case you are using them. Yeah normally  `ident` shouldn't be necessary anymore since `webpack >= 2.2.0`, but in reality it is. You only need the `ident` if `options` contain a `{Function}|require()` statement, so webpack can keep the reference to them internally.
